name: HuskHomesImport
version: '${project.version}'
main: the.huskhomesimport.HuskHomesImport
api-version: '1.20'
commands:
  huskhomesimport:
    permission: op
depend:
  - CMI
  - CMILib
  - HuskHomes
